import java.util.Scanner;

public class App {
    public static void main(String[] args) throws Exception {
        Scanner sc = new Scanner (System.in);

        int x, y, resultado;

        x = sc.nextInt();
        y = sc.nextInt();

        resultado = x + y;

        System.out.println("Soma = " + resultado);

        sc.close();
    }
}

//import java.util.Scanner;

public class Ex3 {
    public static void main(String[] args) throws Exception {
        
    }
}
